### ISSUE TITLE
Questions on state store

### ISSUE THREAD

**Issue by qazwsxedckll** [benc-uk/dapr-store#52]
Why the official doc and your project are using Redis to store data. Won't the data be lost when Redis restarts without AOF and RDB on? If it is true, what should I use. A postgres state store, output Binding or connect database directly.

Even a postgres is used as state store. Dapr still stores data as key-value pairs. The advantages of relational database are totally lost.

 I just want to know your opinions. Thank you.

**Comment by benc-uk** [comment]
Dapr comes "out of the box" with Redis, as it's quick and easy to get started with, run locally etc
I continue to use it in this sample app, again to provide minimal friction to what we're trying to showcase with the sample - which is the Dapr APIs & components, themselves. It's not intended as a best practice or real world implemenation

But the joy of using Dapr is, you can swap out Redis for a persistent store with no change to your code.

Also Dapr state stores are not indented to replace a full database, which is why they have a simple key-value structure. You shouldn't think of a Dapr state store as a database, and this is why the Products service in this sample app uses SQLite
